### ISSUE TITLE
Can you update your app?

### ISSUE THREAD

**Issue by hexiaoyanh** [Generalbrus/BrightLockscreen#1]
it not work on andriod 8.1 , this app is very helpful for me.i very hate the lockscreen shadow, thanks

**Comment by larabr** [comment]
Hey, I don't have Android 8.1 so I cannot work on it. If somebody else can fork and fix the module, then I'll release it.

**Comment by hexiaoyanh** [comment]
all right,i will study android quicky,hope to fix the module,thanks
